export const industries = [
  "Agriculture",
  "Automotive",
  "Biotechnology",
  "Chemical",
  "Construction",
  "Consumer goods",
  "Education",
  "Energy",
  "Environmental technology",
  "Finance",
  "Food and beverage",
  "Healthcare",
  "Hospitality",
  "Information technology",
  "Manufacturing",
  "Media and entertainment",
  "Mining",
  "Pharmaceuticals",
  "Retail",
  "Telecommunications",
  "Transportation",
  "Technology",
  "Utilities",
];

export const stages = [
  {
    id: 1,
    name: "Ideation",
    description:
      "This is the stage where you generate an idea for a new product or service by brainstorming, conducting market research, and identifying customer needs and pain points.",
  },
  {
    id: 2,
    name: "Concept Development",
    description:
      "Here, you refine and develop the idea further by creating a clear definition, developing a business model, and identifying potential target customers. Proof of Concept: In this stage, you create a prototype or model of the product or service to test its feasibility and potential.",
  },
  {
    id: 3,
    name: "Proof of Concept",
    description:
      "In this stage, you create a prototype or model of the product or service to test its feasibility and potential.",
  },
  {
    id: 4,
    name: "Prototype Development",
    description:
      "After the proof of concept stage, a more advanced prototype is developed to test the product or service in more detail.",
  },
  {
    id: 5,
    name: "Product Development",
    description:
      "This is the stage where the final product is developed for commercial use, including product design, engineering, and manufacturing.",
  },
  {
    id: 6,
    name: "Launch",
    description:
      "The product or service is introduced to the market, which can include creating marketing campaigns, pricing strategies, and distribution channels.",
  },
  {
    id: 7,
    name: "Growth",
    description:
      "The product or service should ideally begin to grow in popularity and usage, including expanding distribution, improving customer satisfaction, and developing new features or product lines.",
  },
  {
    id: 8,
    name: "Maturity",
    description:
      "The product or service is well-established and has a loyal customer base, which can include maintaining profitability, optimizing production, and exploring new markets or opportunities.",
  },
  {
    id: 9,
    name: "Decline",
    description:
      "The product or service begins to lose market share and may become less profitable, including identifying the reasons for the decline and potentially discontinuing the product or service.",
  },
];

export const tooltips = {
  marketPotential:
    "This refers to the estimated size and value of the target market for your innovation. It helps determine the potential revenue and profitability of your innovation.",
  targetMarket:
    "This refers to the specific group of people or organizations that your innovation is intended to serve or benefit.",
  marketSize:
    "Market size refers to the total amount of sales or revenue generated by a specific market or industry. It is the total amount of money that consumers spend on goods and services within a particular market or industry during a given time period.",
  demand:
    "The current demand for your innovation refers to how much interest or need there is for your product or service among potential customers. This can be affected by factors such as market trends, competition, and consumer behavior.",
  uniqueSellingProposition:
    "Unique Selling Proposition (USP) is a factor that differentiates a product or service from its competitors and makes it stand out in the market. This can include features, benefits, pricing, or other factors that make the product or service more attractive to potential customers. When identifying your USP, it's important to consider what sets your innovation apart and why customers would choose it over similar products or services.",
  marketingStrategies:
    "This refers to the specific methods or tactics that you plan to use to promote and advertise your innovation to your target audience. Some examples of marketing strategies include social media marketing, search engine optimization, email marketing, content marketing, and paid advertising. It's important to carefully consider which strategies are most appropriate for your target market and budget.",
  timeToPenetrateMarketAndAchieveProfitability:
    "This refers to the amount of time you anticipate it will take for your innovation to gain a significant foothold in the market and start generating profits. This can be influenced by a number of factors, such as the size of the market, level of competition, and the effectiveness of your marketing strategies. It is important to have a realistic estimate of the time required to achieve profitability in order to effectively manage your resources and plan for the future.",
  CompetitivePricingAnalysis:
    "This refers to the price at which you plan to sell your innovation to customers. It's important to research the price points of similar products or services offered by competitors in the market to ensure that your pricing is competitive. Consider factors such as production costs, profit margins, and target market when setting your price. You can also consider offering promotional deals or discounts to attract customers and gain a competitive edge.",
  estimatedCost:
    "The estimated cost of producing the innovation refers to the projected expenses associated with developing and manufacturing the product or service. This can include costs such as research and development, materials, labor, equipment, and marketing.",
  targetSellingPrice:
    "This refers to the price at which you plan to sell your product or service to customers. It should be based on your production costs, competitor pricing, and your target market's willingness to pay. A well-considered target selling price can help ensure profitability and market competitiveness.",
  competition:
    "This refers to the price comparison of your product or service with the similar ones offered by your competitors in the market segment. A thorough analysis of the competitor's pricing strategy helps you to define your own price strategy. You can set the price of your innovation above or below the market average, depending on your unique selling proposition, quality, and production costs. A well-planned pricing strategy can help your innovation stand out in the market and attract customers.",
  pricingFactors:
    "This question is asking you to consider the various factors that went into determining the pricing strategy for your product or service. Factors to consider may include production costs, competitor pricing, target market demographics and their willingness to pay, market demand, and your desired profit margin. By identifying the key factors that influenced your pricing decision, you can better understand and communicate the value proposition of your innovation to potential customers.",
  targetMarketRevenue:
    "This refers to the total amount of revenue generated by the target market for your product or service in a year. To estimate this figure, you will need to identify the size of your target market and the average amount they spend on similar products or services. This information can be used to determine the revenue potential of your innovation and help inform your pricing and marketing strategies.",
  fundingNeeds:
    "'Funding needs' refers to the amount of money required to develop and bring your innovation to the market. This can include costs such as research and development, manufacturing, marketing, and distribution. It's important to carefully consider your funding needs and develop a realistic budget to ensure that you have adequate resources to achieve your goals.",
  fundingNeeded:
    "This refers to the total amount of funding that your innovation requires to start or continue operations. It should include all the costs associated with developing, marketing, and scaling your innovation.",
  useOfFunds:
    "This refers to how you plan to allocate the funds raised through funding. Examples may include product development, marketing and advertising, research and development, hiring, and other operational expenses.",
  potentialSources:
    "This refers to the different sources of funding that you may consider for your innovation. These could include venture capitalists, angel investors, crowdfunding, or government grants. It is important to research and evaluate the options available to you, considering factors such as the amount of funding required, the terms and conditions of funding, and the potential impact on your business.",
  role: "Please enter the team member's role or position in the company.",
  relationshipToTheInnovation:
    "This refers to how the team member is involved in the innovation. For example, they may be a co-founder, a consultant, an investor, or an employee of the company developing the innovation. Providing this information helps us understand the role and importance of the team member in the development and success of the innovation.",
};

export const demandOptions = [
  {
    label: "Low",
    tooltip: "There is little or no demand for your innovation at this time.",
  },
  {
    label: "Moderate",
    tooltip:
      "There is some demand for your innovation, but it is not yet widespread.",
  },
  {
    label: "High",
    tooltip:
      "There is significant demand for your innovation and it is already in use by many people or organizations.",
  },
];

export const timeToPenetrateMarketAndAchieveProfitabilityOptions = [
  "Less than 6 months",
  "6-12 months",
  "1-2 years",
  "2-3 years",
  "More than 3 years",
];
export const competitionOptions = [
  { value: "Low", label: "Few competitors in the target market" },
  { value: "Medium", label: "Some competitors in the target market" },
  { value: "High", label: "Many competitors in the target market" },
  {
    value: "Unknown",
    label: "Not sure about the level of competition",
  },
];
